version: "1.0"
services:
  rabbitmq:
    image: rabbitmq:3.12.14-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - network1
networks:
  network1:
    name: microservice-network
    external: true