apiVersion: v1
kind: Secret
metadata:
  name: auth-server-credentials
  namespace: default
stringData:
  .env: |
    SECRET_KEY=f2b602b6b86e5e3ea605f4fcbd4e97a84fb0776af0ea2231adcb74aa4fbedd5f
    ALGORITHM = HS256
    ACCESS_TOKEN_EXPIRE_MINUTES = 60
    DATABASE_URL=postgresql://postgres:postgres@postgres-db-service:5432/auth
