apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  labels:
    name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgres-db
  template:
    metadata:
      labels:
        service: postgres-db
    spec:
      containers:
        - image: postgres:16.3
          imagePullPolicy: Always
          name: postgres-db
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-db-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-credentials
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-db-credentials
                  key: db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-volume-mount
      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: postgres-db-pvc
