#postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata: 
  name: postgres-db-credentials
  namespace: default
type: Opaque
data:
  #postgres_host: host.minikube.internal
  user: cG9zdGdyZXM=                  # postgres
  db: YXV0aA==                        # auth
  password: cG9zdGdyZXM=              # postgres
  port: NTQzMg==                      # 5432
  host: cG9zdGdyZXMtZGItc2VydmljZQ==  # service name in the postgres-service.yml

# WHAT IS DIFFERENCE BETWEEN DATA AND STRINGDATA IN KUBERNETES?